version: '3'
services:
  user-service:
    image: node:18-alpine3.17
    command: yarn dev
    ports:
      - 8081:8081
    volumes:
      - ./:/source
    working_dir: /source
  postgres:
    image: postgres:16-alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
